In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Praful\Desktop\Pandas\Data\survey_results_public.csv', index_col='Respondent')
schema_df = pd.read_csv(r'C:\Users\Praful\Desktop\Pandas\Data\survey_results_schema.csv', index_col="Column")

In [3]:
df.head(1)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [8]:
schema_df.head()

                                                  QuestionText
Column
Respondent   Randomized respondent ID number (not in order ...
MainBranch   Which of the following options best describes ...
Hobbyist                               Do you code as a hobby?
OpenSourcer        How often do you contribute to open source?
OpenSource   How do you feel about the quality of open sour...

In [9]:
df['ConvertedComp'].head(15)

Respondent
1          NaN
2          NaN
3       8820.0
4      61000.0
5          NaN
6     366420.0
7          NaN
8          NaN
9      95179.0
10     13293.0
11         NaN
12         NaN
13     90000.0
14     57060.0
15         NaN
Name: ConvertedComp, dtype: float64

In [10]:
df['ConvertedComp'].median()

57287.0

In [11]:
df.median()

CompTotal        62000.0
ConvertedComp    57287.0
WorkWeekHrs         40.0
CodeRevHrs           4.0
Age                 29.0
dtype: float64

In [12]:
df.describe()

          CompTotal  ConvertedComp   WorkWeekHrs    CodeRevHrs           Age
count  5.594500e+04   5.582300e+04  64503.000000  49790.000000  79210.000000
mean   5.519014e+11   1.271107e+05     42.127197      5.084308     30.336699
std    7.331926e+13   2.841523e+05     37.287610      5.513931      9.178390
min    0.000000e+00   0.000000e+00      1.000000      0.000000      1.000000
25%    2.000000e+04   2.577750e+04     40.000000      2.000000     24.000000
50%    6.200000e+04   5.728700e+04     40.000000      4.000000     29.000000
75%    1.200000e+05   1.000000e+05     44.750000      6.000000     35.000000
max    1.000000e+16   2.000000e+06   4850.000000     99.000000     99.000000

In [14]:
df['ConvertedComp'].count()

55823

In [16]:
df['Hobbyist'].head(10)

Respondent
1     Yes
2      No
3     Yes
4      No
5     Yes
6     Yes
7      No
8     Yes
9     Yes
10    Yes
Name: Hobbyist, dtype: object

In [18]:
df['Hobbyist'].value_counts()

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [20]:
df['SocialMedia'].head(5)

Respondent
1      Twitter
2    Instagram
3       Reddit
4       Reddit
5     Facebook
Name: SocialMedia, dtype: object

In [21]:
schema_df.loc['SocialMedia']

QuestionText    What social media site do you use the most?
Name: SocialMedia, dtype: object

In [22]:
df['SocialMedia'].value_counts()

Reddit                      14374
YouTube                     13830
WhatsApp                    13347
Facebook                    13178
Twitter                     11398
Instagram                    6261
I don't use social media     5554
LinkedIn                     4501
WeChat 微信                     667
Snapchat                      628
VK ВКонта́кте                 603
Weibo 新浪微博                     56
Youku Tudou 优酷                 21
Hello                          19
Name: SocialMedia, dtype: int64

In [23]:
df['SocialMedia'].value_counts(normalize=True)

Reddit                      0.170233
YouTube                     0.163791
WhatsApp                    0.158071
Facebook                    0.156069
Twitter                     0.134988
Instagram                   0.074150
I don't use social media    0.065777
LinkedIn                    0.053306
WeChat 微信                   0.007899
Snapchat                    0.007437
VK ВКонта́кте               0.007141
Weibo 新浪微博                  0.000663
Youku Tudou 优酷              0.000249
Hello                       0.000225
Name: SocialMedia, dtype: float64

In [26]:
df['Country'].value_counts().head(10)

United States     20949
India              9061
Germany            5866
United Kingdom     5737
Canada             3395
France             2391
Brazil             1948
Poland             1922
Australia          1903
Netherlands        1852
Name: Country, dtype: int64

In [28]:
country_grp = df.groupby(['Country'])

In [30]:
country_grp.get_group('India')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,...,Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult
15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
50,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,NaN,South Asian,No,Too long,Easy
65,I am a developer by profession,Yes,Never,NaN,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",NaN,...,A lot more welcome now than last year,NaN,21.0,Man,No,NaN,NaN,Yes,Appropriate in length,Neither easy nor difficult
68,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Taken an online course in programming or softw...,...,Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,South Asian,No,Appropriate in length,Easy
75,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Courses on technologies you're interested in,27.0,Woman,No,Straight / Heterosexual,NaN,No,Too long,Neither easy nor difficult
78,I am a developer by profession,No,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,...,Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,25.0,Man,No,NaN,NaN,Yes,Appropriate in length,Easy
83,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Industry news about technologies you're intere...,22.0,Man,No,Straight / Heterosexual,South Asian,No,Appropriate in length,Neither easy nor difficult
89,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",India,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,NaN,Man,No,Bisexual,East Asian,Yes,Too short,Easy
90,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,25.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Easy
99,I am a student who is learning to code,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed part-time,India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Somewhat more welcome now than last year,Industry news about technologies you're intere...,21.0,Man,No,Straight / Heterosexual,South Asian,No,Appropriate in length,Neither easy nor difficult
104,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken a part-time in-person course in programm...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Easy
121,I am a student who is learning to code,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,20.0,Man,No,Straight / Heterosexual,South Asian,No,Too long,Neither easy nor difficult
124,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",NaN,...,A lot more welcome now than last year,Tech articles written by other developers;Cour...,27.0,Man,No,Bisexual,South Asian,NaN,Too long,Easy
140,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,25.0,Man,No,Straight / Heterosexual,NaN,NaN,Too long,Easy
169,I am a developer by profession,No,Less than once per year,The quality of OSS and closed source software ...,NaN,India,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Contributed to open source software,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,32.0,Man,No,NaN,East Asian,Yes,Too long,Neither easy nor difficult
174,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Industry news about technologies you're intere...,24.0,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Neither easy nor difficult
176,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Completed an industry certification program (e...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,31.0,Man,No,Straight / Heterosexual,East Asian,Yes,Appropriate in length,Easy
178,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",India,"Yes, full-time",NaN,"Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,28.0,Man,NaN,Bisexual,South Asian,Yes,Too long,Easy
220,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","A business discipline (ex. accounting, finance...",Participated in a full-time developer training...,...,Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Easy
238,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, part-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,31.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Easy
239,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",NaN,...,A lot more welcome now than last year,Courses on technologies you're interested in,30.0,Man,NaN,NaN,NaN,Yes,Appropriate in length,Neither easy nor difficult
263,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,NaN,40.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Neither easy nor difficult
271,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,24.0,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Easy
288,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,NaN,Man,No,Bisexual,South Asian,Yes,Too long,Easy
291,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,NaN,Straight / Heterosexual,South Asian,NaN,Too long,Easy
343,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Participated in online coding competitions (e....,...,Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Woman,No,NaN,NaN,Yes,Too long,Easy
344,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88843,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat more welcome now than last year,Industry news about technologies you're intere...,22.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Easy
88856,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)",Web development or web design,Participated in online coding competitions (e....,...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88869,I am a developer by profession,No,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,NaN,NaN,NaN,NaN,...,A lot more welcome now than last year,Tech articles written by other developers,30.0,Man,No,NaN,South Asian,No,Too long,Neither easy nor difficult
88872,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,NaN,Man,No,NaN,NaN,Yes,NaN,Neither easy nor difficult
14444,NaN,No,Less than once per year,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",India,"Yes, full-time",Some college/university study without earning ...,NaN,NaN,...,Not applicable - I did not use Stack Overflow ...,Tech articles written by other developers;Indu...,NaN,NaN,No,Bisexual,NaN,NaN,Too short,Neither easy nor difficult
20000,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,...,A lot less welcome now than last year,Tech articles written by other developers;Indu...,28.0,Man,No,NaN,South Asian,NaN,Too long,NaN
20567,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",India,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","A natural science (ex. biology, chemistry, phy...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,South Asian,No,Appropriate in length,Easy
20892,NaN,No,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, part-time",NaN,"Another engineering discipline (ex. civil, ele...","Taught yourself a new language, framework, or ...",...,NaN,NaN,43.0,Man,No,NaN,NaN,Yes,Too long,Easy
21826,NaN,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time",NaN,Web development or web design,Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers,22.0,Man,No,NaN,South Asian,Yes,Appropriate in length,Easy
24606,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,NaN,Associate degree,NaN,Taken a part-time in-person course in programm...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25114,NaN,Yes,Never,The quality of OSS and closed source software ...,Employed part-time,India,"Yes, part-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,NaN,...,Just as welcome now as I felt last year,Tech meetups or events in your area,22.0,Man,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult
26419,NaN,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Woman,No,Straight / Heterosexual,NaN,NaN,Too long,Neither easy nor difficult
27229,NaN,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Information systems, information technology, o...","Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,34.0,Man,No,NaN,South Asian,Yes,Too long,Easy
35010,NaN,Yes,Never,The quality of OSS and closed source software ...,NaN,India,No,Primary/elementary school,NaN,Participated in a full-time developer training...,...,NaN,Tech articles written by other developers,NaN,Man,NaN,NaN,South Asian,Yes,Appropriate in length,Neither easy nor difficult
40151,NaN,No,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",NaN,India,No,"Secondary school (e.g. American high school, G...",NaN,NaN,...,A lot more welcome now than last year,Tech meetups or events in your area,NaN,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Neither easy nor difficult
40898,NaN,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Easy
42599,NaN,No,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,...,Not applicable - I did not use Stack Overflow ...,NaN,30.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult

In [34]:
filt = df['Country'] == "India"
df.loc[filt]['SocialMedia'].value_counts()

WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
Hello                          5
WeChat 微信                      5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: SocialMedia, dtype: int64

In [37]:
country_grp['SocialMedia'].value_counts().head(50)

Country              SocialMedia
Afghanistan          Facebook                     15
                     YouTube                       9
                     I don't use social media      6
                     WhatsApp                      4
                     Instagram                     1
                     LinkedIn                      1
                     Twitter                       1
Albania              WhatsApp                     18
                     Facebook                     16
                     Instagram                    13
                     YouTube                      10
                     Twitter                       8
                     LinkedIn                      7
                     Reddit                        6
                     I don't use social media      4
                     Snapchat                      1
                     WeChat 微信                     1
Algeria              YouTube                      42
                     Facebook                     41
                     Twitter                      14
                     LinkedIn                      9
                     I don't use social media      7
                     Instagram                     7
                     Reddit                        2
                     WhatsApp                      2
Andorra              Facebook                      2
                     I don't use social media      2
                     Reddit                        1
                     Snapchat                      1
                     YouTube                       1
Angola               Twitter                       2
                     Facebook                      1
                     YouTube                       1
Antigua and Barbuda  YouTube                       2
                     Facebook                      1
                     Instagram                     1
                     Twitter                       1
                     VK ВКонта́кте                 1
Argentina            WhatsApp                    202
                     Twitter                      80
                     YouTube                      62
                     Instagram                    53
                     Reddit                       50
                     Facebook                     45
                     I don't use social media     22
                     LinkedIn                     16
Armenia              Facebook                     38
                     YouTube                      23
                     LinkedIn                      5
                     Instagram                     3
Name: SocialMedia, dtype: int64

In [39]:
country_grp['SocialMedia'].value_counts().loc['India']

SocialMedia
WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
Hello                          5
WeChat 微信                      5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: SocialMedia, dtype: int64

In [40]:
country_grp['SocialMedia'].value_counts().loc['United States']

SocialMedia
Reddit                      5700
Twitter                     3468
Facebook                    2844
YouTube                     2463
I don't use social media    1851
Instagram                   1652
LinkedIn                    1020
WhatsApp                     609
Snapchat                     326
WeChat 微信                     93
VK ВКонта́кте                  9
Weibo 新浪微博                     8
Hello                          2
Youku Tudou 优酷                 1
Name: SocialMedia, dtype: int64

In [41]:
# country_grp['ConvertedComp'].median()

Country
Afghanistan                                    6222.0
Albania                                       10818.0
Algeria                                        7878.0
Andorra                                      160931.0
Angola                                         7764.0
Antigua and Barbuda                               NaN
Argentina                                     17760.0
Armenia                                       19692.0
Australia                                     79783.0
Austria                                       51559.0
Azerbaijan                                    15858.0
Bahamas                                           NaN
Bahrain                                       15912.0
Bangladesh                                     8764.0
Barbados                                      21000.0
Belarus                                       24000.0
Belgium                                       48120.0
Belize                                            NaN
Benin                                             NaN
Bhutan                                            NaN
Bolivia                                       13020.0
Bosnia and Herzegovina                        18360.0
Botswana                                      38410.0
Brazil                                        18036.0
Brunei Darussalam                              6096.0
Bulgaria                                      28080.0
Burkina Faso                                   8388.0
Burundi                                        3606.0
Cambodia                                      10420.0
Cameroon                                       6288.0
                                               ...
Sri Lanka                                      7476.0
Sudan                                          2016.0
Swaziland                                     62371.0
Sweden                                        56004.0
Switzerland                                   95440.0
Syrian Arab Republic                           2742.0
Taiwan                                        27954.0
Tajikistan                                     4902.0
Thailand                                      30672.0
The former Yugoslav Republic of Macedonia     21996.0
Timor-Leste                                  229500.0
Togo                                           4188.0
Tonga                                             NaN
Trinidad and Tobago                           27828.0
Tunisia                                        6468.0
Turkey                                        17280.0
Turkmenistan                                  27348.0
Uganda                                         5490.0
Ukraine                                       26940.0
United Arab Emirates                          49008.0
United Kingdom                                68041.0
United Republic of Tanzania                    5192.0
United States                                110000.0
Uruguay                                       33850.0
Uzbekistan                                     7176.0
Venezuela, Bolivarian Republic of...           6384.0
Viet Nam                                      11892.0
Yemen                                         11940.0
Zambia                                         5040.0
Zimbabwe                                      19200.0
Name: ConvertedComp, Length: 179, dtype: float64

In [42]:
country_grp['ConvertedComp'].median().loc['Germany']

63016.0

In [44]:
# country_grp['ConvertedComp'].agg(['median', 'mean'])

In [46]:
country_grp['ConvertedComp'].agg(['median', 'mean']).loc['Canada']

median     68705.000000
mean      134018.564909
Name: Canada, dtype: float64

In [49]:
# filt = df['Country'] == 'India'
# df.loc[filt]['LanguageWorkedWith'].str.contains('Python')

In [50]:
filt = df['Country'] == 'India'
df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

3105

In [51]:
country_grp['LanguageWorkedWith'].str.contains('Python').sum()

AttributeError: Cannot access attribute 'str' of 'SeriesGroupBy' objects, try using the 'apply' method

In [52]:
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                                      8
Albania                                         23
Algeria                                         40
Andorra                                          0
Angola                                           2
Antigua and Barbuda                              0
Argentina                                      191
Armenia                                         28
Australia                                      790
Austria                                        338
Azerbaijan                                      17
Bahamas                                          2
Bahrain                                          4
Bangladesh                                     204
Barbados                                         1
Belarus                                         69
Belgium                                        296
Belize                                           1
Benin                                            3
Bhutan                                           1
Bolivia                                         11
Bosnia and Herzegovina                          29
Botswana                                         1
Brazil                                         767
Brunei Darussalam                                0
Bulgaria                                       181
Burkina Faso                                     0
Burundi                                          1
Cambodia                                         9
Cameroon                                        16
                                             ...
Sri Lanka                                      137
Sudan                                           16
Swaziland                                        2
Sweden                                         496
Switzerland                                    460
Syrian Arab Republic                             7
Taiwan                                          88
Tajikistan                                       0
Thailand                                        92
The former Yugoslav Republic of Macedonia        8
Timor-Leste                                      1
Togo                                             1
Tonga                                            0
Trinidad and Tobago                              5
Tunisia                                         40
Turkey                                         371
Turkmenistan                                     6
Uganda                                          47
Ukraine                                        246
United Arab Emirates                            49
United Kingdom                                2384
United Republic of Tanzania                     15
United States                                10083
Uruguay                                         36
Uzbekistan                                      14
Venezuela, Bolivarian Republic of...            28
Viet Nam                                        78
Yemen                                            3
Zambia                                           4
Zimbabwe                                        14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [53]:
country_respondents = df['Country'].value_counts()
country_respondents

United States                            20949
India                                     9061
Germany                                   5866
United Kingdom                            5737
Canada                                    3395
France                                    2391
Brazil                                    1948
Poland                                    1922
Australia                                 1903
Netherlands                               1852
Russian Federation                        1694
Spain                                     1604
Italy                                     1576
Sweden                                    1274
Switzerland                                978
Israel                                     952
Turkey                                     949
Pakistan                                   923
Ukraine                                    868
Austria                                    839
Czech Republic                             764
Romania                                    760
Iran                                       738
Belgium                                    727
China                                      664
Bulgaria                                   659
Mexico                                     642
South Africa                               627
Denmark                                    617
Bangladesh                                 605
                                         ...
Liechtenstein                                3
Democratic People's Republic of Korea        3
Bahamas                                      3
Guinea                                       3
Cape Verde                                   3
Mali                                         3
Lesotho                                      3
Barbados                                     3
Belize                                       3
Lao People's Democratic Republic             3
Guyana                                       3
Gabon                                        2
Malawi                                       2
Bhutan                                       2
San Marino                                   2
Seychelles                                   2
Djibouti                                     2
Sierra Leone                                 2
Liberia                                      2
Tonga                                        1
Dominica                                     1
Chad                                         1
Papua New Guinea                             1
Timor-Leste                                  1
Sao Tome and Principe                        1
Niger                                        1
Saint Vincent and the Grenadines             1
Brunei Darussalam                            1
North Korea                                  1
Saint Kitts and Nevis                        1
Name: Country, Length: 179, dtype: int64

In [54]:
country_uses_python = country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

In [55]:
country_uses_python

Country
Afghanistan                                      8
Albania                                         23
Algeria                                         40
Andorra                                          0
Angola                                           2
Antigua and Barbuda                              0
Argentina                                      191
Armenia                                         28
Australia                                      790
Austria                                        338
Azerbaijan                                      17
Bahamas                                          2
Bahrain                                          4
Bangladesh                                     204
Barbados                                         1
Belarus                                         69
Belgium                                        296
Belize                                           1
Benin                                            3
Bhutan                                           1
Bolivia                                         11
Bosnia and Herzegovina                          29
Botswana                                         1
Brazil                                         767
Brunei Darussalam                                0
Bulgaria                                       181
Burkina Faso                                     0
Burundi                                          1
Cambodia                                         9
Cameroon                                        16
                                             ...
Sri Lanka                                      137
Sudan                                           16
Swaziland                                        2
Sweden                                         496
Switzerland                                    460
Syrian Arab Republic                             7
Taiwan                                          88
Tajikistan                                       0
Thailand                                        92
The former Yugoslav Republic of Macedonia        8
Timor-Leste                                      1
Togo                                             1
Tonga                                            0
Trinidad and Tobago                              5
Tunisia                                         40
Turkey                                         371
Turkmenistan                                     6
Uganda                                          47
Ukraine                                        246
United Arab Emirates                            49
United Kingdom                                2384
United Republic of Tanzania                     15
United States                                10083
Uruguay                                         36
Uzbekistan                                      14
Venezuela, Bolivarian Republic of...            28
Viet Nam                                        78
Yemen                                            3
Zambia                                           4
Zimbabwe                                        14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [56]:
python_df = pd.concat([country_respondents, country_uses_python],axis = 'columns', sort = False)

In [58]:
python_df.head(10)

                Country  LanguageWorkedWith
United States     20949               10083
India              9061                3105
Germany            5866                2451
United Kingdom     5737                2384
Canada             3395                1558
France             2391                1054
Brazil             1948                 767
Poland             1922                 751
Australia          1903                 790
Netherlands        1852                 767

In [60]:
python_df.rename(columns={'Country': 'NumRepondents', 'LanguageWorkedWith': 'NumKnowsPython'}, inplace=True)

In [63]:
python_df.head(10)

                NumRepondents  NumKnowsPython
United States           20949           10083
India                    9061            3105
Germany                  5866            2451
United Kingdom           5737            2384
Canada                   3395            1558
France                   2391            1054
Brazil                   1948             767
Poland                   1922             751
Australia                1903             790
Netherlands              1852             767

In [64]:
python_df['PctKnowsPython'] = (python_df['NumKnowsPython']/python_df['NumRepondents']) * 100

In [65]:
python_df

,NumRepondents,NumKnowsPython,PctKnowsPython
United States,20949,10083,48.131176
India,9061,3105,34.267741
Germany,5866,2451,41.783157
United Kingdom,5737,2384,41.554820
Canada,3395,1558,45.891016
France,2391,1054,44.081974
Brazil,1948,767,39.373717
Poland,1922,751,39.073881
Australia,1903,790,41.513400
Netherlands,1852,767,41.414687
Russian Federation,1694,708,41.794569
Spain,1604,641,39.962594
Italy,1576,625,39.657360
Sweden,1274,496,38.932496
Switzerland,978,460,47.034765
Israel,952,457,48.004202
Turkey,949,371,39.093783
Pakistan,923,251,27.193933
Ukraine,868,246,28.341014
Austria,839,338,40.286055
Czech Republic,764,285,37.303665
Romania,760,253,33.289474
Iran,738,268,36.314363
Belgium,727,296,40.715268
China,664,297,44.728916
Bulgaria,659,181,27.465857
Mexico,642,245,38.161994
South Africa,627,202,32.216906
Denmark,617,246,39.870340
Bangladesh,605,204,33.719008
...,...,...,...
Liechtenstein,3,1,33.333333
Democratic People's Republic of Korea,3,1,33.333333
Bahamas,3,2,66.666667
Guinea,3,2,66.666667
Cape Verde,3,0,0.000000
Mali,3,1,33.333333
Lesotho,3,1,33.333333
Barbados,3,1,33.333333
Belize,3,1,33.333333
Lao People's Democratic Republic,3,0,0.000000
Guyana,3,2,66.666667
Gabon,2,0,0.000000
Malawi,2,0,0.000000
Bhutan,2,1,50.000000
San Marino,2,1,50.000000
Seychelles,2,1,50.000000
Djibouti,2,0,0.000000
Sierra Leone,2,1,50.000000
Liberia,2,0,0.000000
Tonga,1,0,0.000000
Dominica,1,1,100.000000
Chad,1,0,0.000000
Papua New Guinea,1,0,0.000000
Timor-Leste,1,1,100.000000
Sao Tome and Principe,1,1,100.000000
Niger,1,1,100.000000
Saint Vincent and the Grenadines,1,0,0.000000
Brunei Darussalam,1,0,0.000000
North Korea,1,0,0.000000
Saint Kitts and Nevis,1,0,0.000000

In [67]:
python_df.sort_values(by='PctKnowsPython', ascending=False, inplace=True)

In [68]:
python_df.head(15)

                           NumRepondents  NumKnowsPython  PctKnowsPython
Dominica                               1               1      100.000000
Niger                                  1               1      100.000000
Sao Tome and Principe                  1               1      100.000000
Timor-Leste                            1               1      100.000000
Turkmenistan                           7               6       85.714286
Mauritania                             7               5       71.428571
Guyana                                 3               2       66.666667
Bahamas                                3               2       66.666667
Guinea                                 3               2       66.666667
Uganda                                72              47       65.277778
Iceland                               49              30       61.224490
Namibia                                5               3       60.000000
Benin                                  5               3       60.000000
Haiti                                  5               3       60.000000
Congo, Republic of the...              7               4       57.142857

In [69]:
python_df.loc['Japan']

NumRepondents     391.000000
NumKnowsPython    182.000000
PctKnowsPython     46.547315
Name: Japan, dtype: float64